project:
  type: website
  output-dir: docs

website:
  title: "Data-Visuzaliation-Examples"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Charts"
        contents:
          - index.qmd
          - chart_bar.qmd
          - chart_beeswarm.qmd
          - chart_small-multiples.qmd
      - section: "Tables"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

